### ISSUE TITLE
tls support for listeners

### ISSUE THREAD

**Issue by maurorosero** [robertdebock/ansible-role-vault#6]
## Proposed feature

modifications on template config.hcl to support tls on listeners. in this step only configure cert and key files if tls_disable == 0. Previously, copy both files to server before role execution. 

## Rationale

Why is this feature required?
Its, important for security concerns.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Implemented in 4.5.0. Thanks once again!
