### ISSUE TITLE
Remove shell commands, just do assignment expressions in /etc/environment file

### ISSUE THREAD

**Issue by flybyray** [robertdebock/ansible-role-vault#9]
> /etc/environment
This file is specifically meant for system-wide environment variable settings. It is not a script file, but rather consists of assignment expressions, one per line. 
[System-wide environment variables](https://help.ubuntu.com/community/EnvironmentVariables#A.2Fetc.2Fenvironment)

https://github.com/robertdebock/ansible-role-vault/blob/e1e7fa99d53f70b2ed1c37f4a13ded7e8e980b09/tasks/shared.yml#L89

**Comment by robertdebock** [comment]
Ah, thanks.

So, I think you would like to see a key-value combination rather than `export`, something like this:

```
VAULT_ADDR={{ vault_api_addr }}
```

Regards,

Robert.

**Comment by flybyray** [comment]
In short (or in most cases) yes.

It depends a little bit.

> Start with code that barely works. **That means some assumptions will be made.**
https://robertdebock.nl/my-manifesto.html#simplicity
=> YES

Details:

> The initial environment of the shell is populated in various
       ways, such as definitions from /etc/environment that are
       processed by pam_env(8) for all users at login time (on systems
       that employ pam(8)).
https://man7.org/linux/man-pages/man7/environ.7.html

> Second a file (/etc/environment by default) with simple KEY=VAL
       pairs on separate lines will be read.
https://man7.org/linux/man-pages/man8/pam_env.8.html

The pam_env allows some overrides but I do not think someone will handle this on this level.

**Comment by robertdebock** [comment]
Hm, after reading a bit more, I think a location as /etc/profile.d/vault.sh is a better destination.

Thanks for pointing out /etc/environment is 'reserved' for different purposes.

I'll work on a commit for this.
